//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Satis = new HashSet<Sati>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Soyad { get; set; }
        public string Tc { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public string Meslek { get; set; }
        public string CepTel { get; set; }
        public string IsTel { get; set; }
        public string Email { get; set; }
        public string Sehir { get; set; }
        public string Adres { get; set; }
        public string EhliyetNo { get; set; }
        public string EhliyetTur { get; set; }
        public Nullable<System.DateTime> EhliyetAlisTarih { get; set; }
        public string Notlar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sati> Satis { get; set; }
    }
}
