//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sati
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<int> RezervasyonId { get; set; }
        public Nullable<int> KiraId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Kira Kira { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Rezervasyon Rezervasyon { get; set; }
        public virtual User User { get; set; }
    }
}
